apiVersion: apps/v1
kind: Deployment
metadata: 
  name: barom
  namespace: aemet
  labels:
    app: barom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barom
  template:
    metadata:
      labels:
        app: barom
    spec:
      containers:
        - name: barom
          image: richifor/barom:v1
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-barometrico
  namespace: aemet
  labels:
    app: barom
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 7000
  selector:
    app: barom
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: barom
  namespace: aemet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: servicio-barometrico
                port:
                  number: 80
